"""Respawn drivable cars cleanly while keeping parked curbside car props.
Places lane-aware drivable cars so traffic feels denser without stacking.
"""
import unreal
import random
import math
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.append(SCRIPT_DIR)

import vehicle_realism

random.seed(99)
les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
eas = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)

les.load_level("/Game/Maps/TestMap")

# grid params (match build_city.py)
N = 7
BLOCK = 2000.0
ROAD = 600.0
STEP = BLOCK + ROAD
SPAN = N * STEP
START = -SPAN / 2 + STEP / 2
def cx(i):
    return START + i * STEP
vroads = [(cx(i) + cx(i + 1)) / 2.0 for i in range(N - 1)]
hroads = [(cx(j) + cx(j + 1)) / 2.0 for j in range(N - 1)]
LX0, LX1 = cx(4) - STEP / 2, cx(6) + STEP / 2
LY0, LY1 = cx(0) - STEP / 2, cx(1) + STEP / 2
def over_lake(x, y):
    return LX0 - 300 < x < LX1 + 300 and LY0 - 300 < y < LY1 + 300

# Find the REAL PlayerStart so no car spawns on top of the player.
SPAWN = (0.0, 0.0)
for a in eas.get_all_level_actors():
    if a.get_class().get_name() == "PlayerStart":
        L = a.get_actor_location()
        SPAWN = (L.x, L.y)
        break
unreal.log("[Cars] PlayerStart at {}".format(SPAWN))
SPAWN_CLEAR = 1300.0   # no car within this radius of the player spawn

# clear existing drivable cars; parked City_Car_* props are generated by
# populate.py and should remain as street detail.
removed = 0
for a in list(eas.get_all_level_actors()):
    lbl = a.get_actor_label()
    if lbl.startswith("City_DriveCar_"):
        eas.destroy_actor(a)
        removed += 1
unreal.log("[Cars] cleared {} old drivable cars".format(removed))

car_mats = vehicle_realism.load_vehicle_paint_materials()
real_car_meshes = vehicle_realism.load_vehicle_meshes()
unreal.log("[Cars] real vehicle meshes available: {}".format(len(real_car_meshes)))

# Account for traffic generated by add_ai_traffic.py when this script is rerun
# later. Otherwise the replacement drivable fleet can overlap existing traffic.
placed = []
for actor in eas.get_all_level_actors():
    if actor.get_actor_label().startswith("City_TrafficCar_"):
        location = actor.get_actor_location()
        placed.append((location.x, location.y))
unreal.log("[Cars] reserved {} existing traffic-car positions".format(len(placed)))
MIN_GAP = 650.0
# Keep one enterable player car; the moving fleet belongs to add_ai_traffic.py
# / AProceduralTrafficManager. Do not fill live lanes with stationary pawns.
TARGET_CARS = 1
LANE_OFFSET = 150.0

def far_enough(x, y):
    for (px, py) in placed:
        if math.hypot(x - px, y - py) < MIN_GAP:
            return False
    return True

def candidate():
    if random.random() < 0.5:
        lane = random.choice([-LANE_OFFSET, LANE_OFFSET])
        x = random.choice(vroads) + lane + random.uniform(-18, 18)
        y = random.uniform(-SPAN / 2 + 540, SPAN / 2 - 540)
        yaw = 90.0 if lane > 0 else 270.0
    else:
        lane = random.choice([-LANE_OFFSET, LANE_OFFSET])
        x = random.uniform(-SPAN / 2 + 540, SPAN / 2 - 540)
        y = random.choice(hroads) + lane + random.uniform(-18, 18)
        yaw = 0.0 if lane < 0 else 180.0
    return x, y, yaw

# One car in a recessed curb bay near the player, outside the ±150 live lanes.
nearest_vroad = min(vroads, key=lambda value: abs(value - SPAWN[0]))
parking_side = -1.0 if SPAWN[0] <= nearest_vroad else 1.0
guaranteed = (nearest_vroad + parking_side * 410.0, SPAWN[1] + 300.0, 90.0)

spots = []
if far_enough(guaranteed[0], guaranteed[1]):
    spots.append(guaranteed)
    placed.append((guaranteed[0], guaranteed[1]))
else:
    unreal.log_warning("[Cars] nearby slot already occupied by traffic; using generated positions")
attempts = 0
while len(spots) < TARGET_CARS and attempts < 7000:
    attempts += 1
    x, y, yaw = candidate()
    if over_lake(x, y):
        continue
    if math.hypot(x - SPAWN[0], y - SPAWN[1]) < SPAWN_CLEAR:
        continue   # keep well clear of the player spawn
    if not far_enough(x, y):
        continue
    spots.append((x, y, yaw))
    placed.append((x, y))

cars = 0
real_cars = 0
for (x, y, yaw) in spots:
    car = eas.spawn_actor_from_class(unreal.SprawlCar,
                                     unreal.Vector(x, y, 175),
                                     unreal.Rotator(roll=0.0, pitch=0.0, yaw=yaw))
    car.set_actor_label("City_DriveCar_{}".format(cars))
    car.set_editor_property("auto_drive", False)
    if vehicle_realism.configure_animated_car(car, cars, car_mats):
        real_cars += 1
    elif vehicle_realism.configure_drivable_car(car, cars, real_car_meshes, car_mats):
        real_cars += 1
    cars += 1
unreal.log("[Cars] spawned {} well-spaced drivable cars".format(cars))
unreal.log("[Cars] applied real meshes and varied paint to {} drivable cars".format(real_cars))

saved = les.save_current_level()
unreal.log("[Cars] level saved: {}. DONE".format(saved))
