"""Respawn drivable cars cleanly while keeping parked curbside car props.
Places lane-aware drivable cars so traffic feels denser without stacking.
"""
import unreal
import random
import math
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.append(SCRIPT_DIR)

import vehicle_realism

random.seed(99)
les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
eas = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)

les.load_level("/Game/Maps/TestMap")

# grid params (match build_city.py)
N = 7
BLOCK = 2000.0
ROAD = 600.0
STEP = BLOCK + ROAD
SPAN = N * STEP
START = -SPAN / 2 + STEP / 2
def cx(i):
    return START + i * STEP
vroads = [(cx(i) + cx(i + 1)) / 2.0 for i in range(N - 1)]
hroads = [(cx(j) + cx(j + 1)) / 2.0 for j in range(N - 1)]
LX0, LX1 = cx(4) - STEP / 2, cx(6) + STEP / 2
LY0, LY1 = cx(0) - STEP / 2, cx(1) + STEP / 2
def over_lake(x, y):
    return LX0 - 300 < x < LX1 + 300 and LY0 - 300 < y < LY1 + 300

# Find the REAL PlayerStart so no car spawns on top of the player.
SPAWN = (0.0, 0.0)
for a in eas.get_all_level_actors():
    if a.get_class().get_name() == "PlayerStart":
        L = a.get_actor_location()
        SPAWN = (L.x, L.y)
        break
unreal.log("[Cars] PlayerStart at {}".format(SPAWN))
SPAWN_CLEAR = 1300.0   # no car within this radius of the player spawn

# clear existing drivable cars; parked City_Car_* props are generated by
# populate.py and should remain as street detail.
removed = 0
for a in list(eas.get_all_level_actors()):
    lbl = a.get_actor_label()
    if lbl.startswith("City_DriveCar_"):
        eas.destroy_actor(a)
        removed += 1
unreal.log("[Cars] cleared {} old drivable cars".format(removed))

car_mats = vehicle_realism.load_vehicle_paint_materials()
real_car_meshes = vehicle_realism.load_vehicle_meshes()
unreal.log("[Cars] real vehicle meshes available: {}".format(len(real_car_meshes)))

placed = []
MIN_GAP = 650.0
TARGET_CARS = 28
LANE_OFFSET = 150.0

def far_enough(x, y):
    for (px, py) in placed:
        if math.hypot(x - px, y - py) < MIN_GAP:
            return False
    return True

def candidate():
    if random.random() < 0.5:
        lane = random.choice([-LANE_OFFSET, LANE_OFFSET])
        x = random.choice(vroads) + lane + random.uniform(-18, 18)
        y = random.uniform(-SPAN / 2 + 540, SPAN / 2 - 540)
        yaw = 90.0 if lane > 0 else 270.0
    else:
        lane = random.choice([-LANE_OFFSET, LANE_OFFSET])
        x = random.uniform(-SPAN / 2 + 540, SPAN / 2 - 540)
        y = random.choice(hroads) + lane + random.uniform(-18, 18)
        yaw = 0.0 if lane < 0 else 180.0
    return x, y, yaw

# one car down the street from the player spawn (clear of it)
guaranteed = (SPAWN[0] + 150, SPAWN[1] + 1550, 90.0)

spots = [guaranteed]
placed.append((guaranteed[0], guaranteed[1]))
attempts = 0
while len(spots) < TARGET_CARS and attempts < 7000:
    attempts += 1
    x, y, yaw = candidate()
    if over_lake(x, y):
        continue
    if math.hypot(x - SPAWN[0], y - SPAWN[1]) < SPAWN_CLEAR:
        continue   # keep well clear of the player spawn
    if not far_enough(x, y):
        continue
    spots.append((x, y, yaw))
    placed.append((x, y))

cars = 0
real_cars = 0
for (x, y, yaw) in spots:
    car = eas.spawn_actor_from_class(unreal.SprawlCar,
                                     unreal.Vector(x, y, 175),
                                     unreal.Rotator(0, 0, yaw))
    car.set_actor_label("City_DriveCar_{}".format(cars))
    if vehicle_realism.configure_drivable_car(car, cars, real_car_meshes, car_mats):
        real_cars += 1
    cars += 1
unreal.log("[Cars] spawned {} well-spaced drivable cars".format(cars))
unreal.log("[Cars] applied real meshes and varied paint to {} drivable cars".format(real_cars))

saved = les.save_current_level()
unreal.log("[Cars] level saved: {}. DONE".format(saved))
