// The Connected Sprawl - Runtime bridge for Unreal Panel Cloth assets.

#pragma once

#include "Components/ActorComponent.h"
#include "CoreMinimal.h"
#include "UObject/SoftObjectPtr.h"
#include "SprawlPanelClothModule.generated.h"

class AActor;
class UChaosClothAssetBase;
class UChaosClothComponent;
class UPhysicsAsset;
class USkeletalMeshComponent;

/**
 * With -SprawlPanelClothPreview, loads the editor-authored Zarri hoodie and
 * binds Chaos Cloth to the live MetaHuman body. Normal launches and missing or
 * invalid cloth assets deliberately retain the rigid streetwear fallback.
 */
UCLASS(ClassGroup=(Sprawl), meta=(BlueprintSpawnableComponent))
class CONNECTEDSPRAWL_API USprawlPanelClothModule : public UActorComponent
{
	GENERATED_BODY()

public:
	USprawlPanelClothModule();

	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

	UFUNCTION(BlueprintCallable, Category="Connected Sprawl|Panel Cloth")
	bool ApplyToMetaHuman(AActor* VisualActor, USkeletalMeshComponent* BodyMesh);

	UFUNCTION(BlueprintCallable, Category="Connected Sprawl|Panel Cloth")
	void ClearPanelCloth();

	UFUNCTION(BlueprintPure, Category="Connected Sprawl|Panel Cloth")
	bool IsPanelClothActive() const;

	UFUNCTION(BlueprintPure, Category="Connected Sprawl|Panel Cloth")
	FSoftObjectPath GetConfiguredAssetPath() const;

private:
	/** Generated by the ConnectedSprawlEditor Panel Cloth authoring command. */
	UPROPERTY(EditAnywhere, Category="Connected Sprawl|Panel Cloth")
	TSoftObjectPtr<UChaosClothAssetBase> PanelClothAsset;

	/** MetaHuman collision primitives used by the hoodie simulation. */
	UPROPERTY(EditAnywhere, Category="Connected Sprawl|Panel Cloth")
	TSoftObjectPtr<UPhysicsAsset> CollisionPhysicsAsset;

	UPROPERTY(Transient)
	TObjectPtr<UChaosClothComponent> ClothComponent;
};
